### ISSUE TITLE
TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by DR-DinoMight** [asos-craigmorten/opine#116]
# Issue

Setup:

- Deno Version: deno 1.9.0 (release, x86_64-unknown-linux-gnu)
- v8 Version: v8 9.1.269.5
- Typescript Version: 4.2.2
- Opine Version: opine@1.2.0

## Details

I've been building a   web app and have route files setup similar to:

```
import apiRouter from "./routes/api.js";

app.use("/", appRouter);
...
```

and the route file has 
```
...standard import 
const router = Router();

//Get home page.
router.get("/", (_req, res, _next) => {
  res.json("hello world");
});
```

Upon running Deno I get the following error

```
Something Broke!
 TypeError: Cannot read property 'get' of undefined
    at Response.json (https://deno.land/x/opine@1.2.0/src/response.ts:409:26)
    at file:///home/forge/stream.m4p.uk/routes/app.js:13:8
    at Layer.handle [as handle_request] (https://deno.land/x/opine@1.2.0/src/router/layer.ts:76:11)
    at next (https://deno.land/x/opine@1.2.0/src/router/route.ts:104:13)
    at Route.dispatch (https://deno.land/x/opine@1.2.0/src/router/route.ts:79:3)
    at Layer.handle [as handle_request] (https://deno.land/x/opine@1.2.0/src/router/layer.ts:76:11)
    at https://deno.land/x/opine@1.2.0/src/router/index.ts:267:24
    at Function.process_params (https://deno.land/x/opine@1.2.0/src/router/index.ts:334:12)
    at next (https://deno.land/x/opine@1.2.0/src/router/index.ts:256:10)
    at Function.handle (https://deno.land/x/opine@1.2.0/src/router/index.ts:155:3)
```

Sorry the code is pretty vague but I don't think the rest helps, It is worth noting that as soon as I downgrade Deno to say `1.8.3` it works

**Comment by cmorten** [comment]
Hey @DR-DinoMight 👋 

I _think_ this might be the same issue as https://github.com/asos-craigmorten/opine/issues/110, can you try upgrading Opine to one of the latest versions ( `^1.3.0` ) and see if that resolves the issue?

**Comment by DR-DinoMight** [comment]
Thanks for the quick reply!

I'm sorry I totally didn't see this issue!

Yes, this was the fix! Everything is working again! 

Thanks 😀
